title: Jon Gjengset
email: jon@thesquareplanet.com
description: >
  PhD Student, Software Engineer and problem solver
baseurl: ""
url: "https://thesquareplanet.com"
permalink: /blog/:title/
include: [".well-known"]

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, vendor, _site, public]
