title: Jon Gjengset
email: jon@thesquareplanet.com
description: >
  PhD Student, Software Engineer and problem solver
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://thesquareplanet.com"

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, vendor, _site, public]
